from Polygon import Polygon

class Rectangle(Polygon):

    # Constructor for the Rectangle class that accepts coordinates, height, and width.
    def __init__(self, pointx, pointy, height, width):

        # Calls the constructor of the Polygon class, passing the points generated by _setup_points.
        super().__init__(self._setup_points(pointx, pointy, height, width))
    
    # Method to calculate the points (vertices) of the rectangle.
    def _setup_points(self, pointx, pointy, height, width):
        
        # point1 is the starting point (top-left corner).
        point1 = (pointx, pointy)

        point2 = (point1[0], point1[1] - height)

        point3 = (point2[0] + width, point2[1])

        point4 = (point1[0] + width, point1[1])

        # Returning the list of points that define the rectangle.
        return [point1, point2, point3, point4]



