from Polygon import Polygon

class Triangle(Polygon):

    # Constructor for the Triangle class that accepts coordinates, height, and width.
    def __init__(self, pointx, pointy, height, width):

        # Calls the constructor of the Polygon class, passing the points generated by _setup_points.
        super().__init__(self._setup_points(pointx, pointy, height, width))

    # Method to calculate the points (vertices) of the triangle.
    def _setup_points(self, pointx, pointy, height, width):

        # point1 is the top-left corner of the triangle (starting point).
        point1 = (pointx, pointy)

        point2 = (point1[0], point1[1] - height)

        point3 = (point1[0] + width, point2[1])

        # Returning the list of points that define the triangle.
        return [point1, point2, point3]